name: Create Release

# on:
#   push:
#     branches:
#       - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Configure Git credentials
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global credential.helper store
        echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build gitpython packaging

    - name: Generate new version
      id: generate_version
      run: python .github/release.py

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: steps.generate_version.outputs.version != ''
      with:
        tag_name: ${{ steps.generate_version.outputs.version }}
        generate_release_notes: true

    - name: Build and publish
      if: steps.generate_version.outputs.version != ''
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m build
        twine upload dist/*
